### ISSUE TITLE
"“Servez” can’t be opened because Apple cannot check it for malicious software."

### ISSUE THREAD

**Issue by huangj008** [greggman/servez#11]
"This software needs to be updated. Contact the developer for more information." 

Anyone run into this issue?

![image](https://user-images.githubusercontent.com/48764041/136822531-dbbcb4e8-249c-4f09-bb62-c46137701f2f.png)

**Comment by greggman** [comment]
try 1.9.1

https://github.com/greggman/servez/releases/download/v1.9.0/Servez-1.9.1.dmg
