### ISSUE TITLE
Display a QR code

### ISSUE THREAD

**Issue by larryw3i** [greggman/servez#12]
You forgot one thing: qrcode. @greggman

**Comment by greggman** [comment]
not a bad idea. Unfortunately I have no idea what code to generate. I can generate `http://<your-up-address>:<port>` but that assumes the page you want to go to is at the root document. For me, that's almost never true but maybe it is for others?

**Comment by larryw3i** [comment]
@greggman  Print QR code of url in the terminal, and then if the mobile phone and the computer are on the same LAN, the mobile phone can scan the code and browse the files, I think it's quite convenient.

**Comment by larryw3i** [comment]
servez is perfect, I want to contribute. Unfortunately, I  haven't nodejs development experience.😂

**Comment by greggman** [comment]
Are you using the node version or the Electron version?

**Comment by greggman** [comment]
To put it another way, are you using the command line version of servez or the app version?

**Comment by larryw3i** [comment]
> To put it another way, are you using the command line version of servez or the app version?

Yes, I use cli version.

**Comment by greggman** [comment]
ok then, update to the latest and use `servez --qr`

**Comment by larryw3i** [comment]
Extremely amazing!

**Comment by larryw3i** [comment]
In fact, using the mobile version of Firefox browser can not recognize the QR code, I think this QR code should be square.   
![Screenshot from 2022-02-28 20-07-53](https://user-images.githubusercontent.com/24457116/155982732-46713211-1f3e-4bd9-b5b2-87f80a1b0646.png)

**Comment by greggman** [comment]
you can try the latest but to be honest there is no way to guarantee a square image in the terminal since it's up to the user to select a font.

**Comment by synthic** [comment]
Just a note, QR codes require a white margin around them to be readable by most apps.
