### ISSUE TITLE
folder listings and directories - doesn't add closing "/"

### ISSUE THREAD

**Issue by patrickhlauke** [greggman/servez#2]
Running Servez to initially show its own automatically generated directory listing, if I then follow a link to a directory, the resulting url is missing the closing slash. So, say from the initial listing I go to a folder called "touch", the URL I land on is http://localhost:8080/touch (no slash). This then messes up any links/calls for resources that use "./", "../" or are called without extra path info as they're in the same directory.

Not sure if this is something that can be fixed here or if it's due to some other component used...

**Comment by patrickhlauke** [comment]
And similarly, if I manually type in a directory without the closing slash, it doesn't automagically add it at the end (like, say, Apache would do)

**Comment by greggman** [comment]
Does it need to add the `/`?  I'm sure this is relatively easy to fix, I'm just asking why it's important before I look into it.

**Comment by greggman** [comment]
Thanks for pointing out the issue. I think it's fixed. Please try it

https://github.com/greggman/servez/releases/latest

**Comment by patrickhlauke** [comment]
Wonderful, works perfectly. Thanks for the super-speedy fix 👍
