### ISSUE TITLE
recent used folders/ports 

### ISSUE THREAD

**Issue by riverfeya** [greggman/servez#5]
will be good if it have list for recent folders/ports 

or start from CLI with attributes folder , ports

thank you for Servez!

**Comment by greggman** [comment]
recent folders/ports is a nice idea

For command line though rather than duplicating effort I'd suggest you install [node.js](https://nodejs.org) and then use [http-server](https://www.npmjs.com/package/http-server).

**Comment by riverfeya** [comment]
thank you!

i mean something like:

servez.exe <my first project folder>:8080
servez.exe <my second project folder>:8181
...
servez.exe <my n`s project folder>:8n8n

i use more than one project (documentations) and serves can run it all but node/http - can`t o.o

and i need pass folder,port every time for every project (

well if it will can be like windows shortcut startup options ^^

**Comment by greggman** [comment]
so [the latest version](https://github.com/greggman/servez/releases/latest) supports arguments.

Arguably if you really want a command line verison you should run [the command line version](https://github.com/greggman/servez-cli)

But, you can also use arguments to the app version (like if you want to make windows shortcuts). 

Examples

```
servez.exe -- --port=8080 c:\Users\<username>\someprojectfolder
servez.exe -- --port=8081 c:\Users\<username>\someotherprojectfolder
servez.exe -- c:\Users\<username>\someyetanotherprojectfolder
```

notice the extra `--`. It's important.

**Comment by riverfeya** [comment]
Its Grate!
Thank you very much! ^^
