### ISSUE TITLE
mssing cached-fake-cert.pem with https on Windows

### ISSUE THREAD

**Issue by Blubberblub** [greggman/servez#6]
I tried to hosting with https on Windows and servez complains about the certificate missing. On MacOS everything works just fine. Can someone give me a hint what  the issue could be?

ERROR: [object Object] ENOENT, node_modules\servez-lib\lib\cached-fake-cert.pem not found in C:\Users\my_username\AppData\Local\Programs\Servez\resources\app.asar Error: ENOENT, node_modules\servez-lib\lib\cached-fake-cert.pem not found in C:\Users\Tim\AppData\Local\Programs\Servez\resources\app.asar

Edit: using the commandline version installed via npm workes on Windows 10

**Comment by greggman** [comment]
it's a bug. I'll look into fixing it

The [command line version](https://github.com/greggman/servez-cli) seems to work on Windows

**Comment by Blubberblub** [comment]
Thanks for the quick info. Thanks for the awesesome tool in general! =) As stated above the commandline version works right now.

**Comment by greggman** [comment]
I think it's fixed. You can try the latest release.

https://github.com/greggman/servez/releases/latest

**Comment by Blubberblub** [comment]
It's working! Thank you. =)
